version: '2.1'

orbs:
  docker: circleci/docker@2.4.0

jobs:
  build-and-push:
    environment:
      DOCKER_IMAGE: 2808zl/phimmoi48h
      DOCKERFILE_PATH: ./docker/Dockerfile

    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: DOCKER_USER
          docker-password: DOCKER_PASSWORD
      - run:
          name: Set DOCKER_TAGS
          command: |
            export DOCKER_TAGS=$(echo "${CIRCLE_BRANCH//\//-}-${CIRCLE_BUILD_NUM}-${CIRCLE_SHA1}" | cut -c 1-7)
      - docker/build:
          image: $DOCKER_IMAGE
          dockerfile: ${DOCKERFILE_PATH}
          tag: $DOCKER_TAGS
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAGS
      - run:
          name: Tag and Push Latest
          command: |
            if [[ "${CIRCLE_BRANCH}" =~ .*main.* ]]; then
              docker tag ${DOCKER_IMAGE}:${DOCKER_TAGS} ${DOCKER_IMAGE}:latest
              docker push ${DOCKER_IMAGE}:latest
            fi
      - run:
          name: Clean up Docker Image
          command: |
            docker image rm ${DOCKER_IMAGE}:${DOCKER_TAGS}
      - run:
          name: Display Digest
          command: |
            echo "Digest is: $(cat /tmp/digest.txt)"

workflows:
  build-deploy:
    jobs:
      - build-and-push:
          filters:
            branches:
              only:
                - circleci-project-setup
