version: '2.1'

orbs:
  docker: circleci/docker@2.4.0

jobs:
  build-and-push:
    environment:
      DOCKER_IMAGE: 2808zl/phimmoi48h
      DOCKER_TAGS: latest
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: DOCKER_USER
          docker-password: DOCKER_PASSWORD
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAGS
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAGS
      - run:
          name: Display Digest
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

workflows:
  build-deploy:
    jobs:
      - build-and-push:
